app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_siz: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "192.168.1.102"
  port: 3306
  user: "root"
  password: "12345678"
  dbname: "sql_demo"
  max_open_conns: 200
  max_idle_conns: 500
  